### ISSUE TITLE
Backdoor in backdoors

### ISSUE THREAD

**Issue by Abdulrah33m** [backdoorhub/shell-backdoor-list#3]
Hello there, 
I just want to mention that I've checked some of the shells in this repository and I can see that there has been a backdoor that allows attacker to bypass the password authentication in each one of them.
It would be great if you can check them again and re-upload clean shells.

**Comment by kingsalman99** [comment]
Thats True Bro ,Recode LoL

**Comment by kingsalman99** [comment]
H

> Halo,
> saya hanya ingin menyebutkan bahwa saya telah memeriksa beberapa shell di repositori ini dan saya dapat melihat bahwa telah ada pintu belakang yang memungkinkan penyerang untuk mem-bypass otentikasi kata sandi di masing-masingnya.
> Akan lebih bagus jika Anda bisa memeriksanya lagi dan mengunggah kembali kerang bersih.

Lol , Script Kiddies ,can Only Recode
